### ISSUE TITLE
LayerNormKernelImpl" not implemented for 'Half'

### ISSUE THREAD

**Issue by liuxy1103** [ModelTC/Outlier_Suppression_Plus#1]
return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'

**Comment by wimh966** [comment]
Hello, I think it's probably that your device does not support FP16 (Half) calculation. One way is to run the model on FP32 instead of FP16. Their results are similar.
