### ISSUE TITLE
[Bug] Weight did not change after quantization

### ISSUE THREAD

**Issue by ChenMnZ** [ModelTC/Outlier_Suppression_Plus#2]
I run the code with the given command. 

I found that the quantizer did not be activated, then the weight was not successfully quantified.

**Comment by wimh966** [comment]
Hello, enable_quantization function has been adopted here. https://github.com/ModelTC/Outlier_Suppression_Plus/blob/2156bf2d892494bb5c77e3cab3c03a9a788930f2/lm_eval/evaluator.py#L276C1-L276C1. So, they have been quantized.

**Comment by ChenMnZ** [comment]
Thank you for your response.

I wonder if this repo supports w6a6?
