### ISSUE TITLE
How to use Multiple GPUs for Large model Inference

### ISSUE THREAD

**Issue by liuxy1103** [ModelTC/Outlier_Suppression_Plus#3]
Althoug you provide a comand for CUDA_VISIBLE_DEVICES=0,1,2,3, I do NOT find the data parallel or model parallel codes for this settings,.
Could you provide more instruction about how to implement inference of the Blomm-176B, a such huge model

**Comment by wimh966** [comment]
Hi, I feel very sorry for the late reply. But the code of model parallel is in the lm_eval/models, where you can find a dispatch function in it. To run the big bloom model, you only need to assign the GPUs, then the code will automatically dispatch parameters with balanced memory to different GPUs for you.
