### ISSUE TITLE
provide relevant code for distribution analysis of model output

### ISSUE THREAD

**Issue by vtars** [ModelTC/Outlier_Suppression_Plus#6]
Could you please provide relevant code for distribution analysis of model output? thx！

**Comment by wimh966** [comment]
Hello, thank you for your question. To do this, you can create an empty observer in the observer.py file, e.g., CollectObserver. The code will automatically insert the observer after the (to-be-quantized) output. Then, just put the analysis like the drawing, printing, or others you want in the forward function of the Collect Observer. Last, enable the calibration but not the quantization (enable_calibration_woquantization) and provide the sample data, you will get the results.
